//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHoc()
        {
            this.Diems = new HashSet<Diem>();
        }

        
        [Required(ErrorMessage = "*")]
        [Display(Name = "Mã môn học")]
        public int MonHocID { get; set; }

       
        [Required(ErrorMessage = "*")]
        [Display(Name = "Tên môn học")]
        public string Ten { get; set; }

       
        [Required(ErrorMessage = "*")]
        [Display(Name = "Số tín chỉ")]
        public int SoTinChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diem> Diems { get; set; }
    }
}
