//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.Diems = new HashSet<Diem>();
        }
        [Required(ErrorMessage = "*")]
        [Display(Name = "Mã sinh viên")]
        public int SinhVienID { get; set; }

        
        [Required(ErrorMessage = "*")]
        [Display(Name = "Lớp")]
        public string Lop { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Họ tên")]
        public string HoTen { get; set; }
    
        public virtual ICollection<Diem> Diems { get; set; }
    }
}
